# Базовый образ для Python
FROM python:3.9

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем все необходимые файлы
COPY ../requirements/req_app.txt . 

COPY ../src/config.py .  
COPY ../src/app.py .

# Устанавливаем зависимости
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r req_app.txt

# Команда для запуска приложения Streamlit
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
