# Базовый образ для Python
FROM python:3.9

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /app

# Копируем все необходимые файлы
COPY ../requirements/req_model.txt .

COPY ../src/config.py .  
COPY ../src/model.py .

# Устанавливаем зависимости
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r req_model.txt

# Команда для запуска приложения Streamlit
CMD ["python", "model.py"]
